### ISSUE TITLE
Samples are tricky to run

### ISSUE THREAD

**Issue by STARasGAMES** [xZenvin/UnitySettingsFramework#1]
Hi

I tried to run the Settings Menu Demo, and turns out it's not possible to try samples without **manually** moving them from `Packages/` to `Assets/` folder using Explorer. 

![image](https://github.com/xZenvin/UnitySettingsFramework/assets/23558898/7b39da07-72e5-424b-95b9-a3fb0f01c5b2)
Yes, these `Import` buttons actually import assets to the `Assets/` folder, but scene references scripts that are located in `Packages/SettingsFramework/Samples` folder, and they are not compiled by Unity most likely because Samples folder doesn't have Assembly Definition file. 

I opened the imported scene
![image](https://github.com/xZenvin/UnitySettingsFramework/assets/23558898/2366cbf2-3abb-409d-ba97-9ee0e299d6e4)

But scripts do not compile and scene references scripts from the `Package/../Samples` folder.
![image](https://github.com/xZenvin/UnitySettingsFramework/assets/23558898/211a46ed-cb16-4a83-a8bf-1f6b4fbcfcb1)

My suggestion is to rename folder `Samples/` to `~Samples/` - that way Unity doesn't recognize assets from the package's source folder.

Unity 2022.3.3f1, Installed as an embedded package.

**Comment by zenvin-dev** [comment]
Thanks for bringing this to my attention!
I renamed `Samples/` to `Samples~/` (not `~Samples/` as suggested), to comply with the [Unity package samples guidelines](https://docs.unity3d.com/Manual/cus-samples.html).

See commit 3656193da09a71a9a6e65a330eb29dcfbbc57bf0.
