### ISSUE TITLE
 How to configure dependencies between options? For example, whether option B is displayed depends on option A.

### ISSUE THREAD

**Issue by YzZ-ZzY** [xZenvin/UnitySettingsFramework#3]

**Comment by zenvin-dev** [comment]
Right now, you would have to reference the dependency in every dependee and subscribe to their respective change event during Setting initialization. Then you would need to have your event handler react to any changes by updating the dependee's `Visibility` (see below for an example).

I am aware that this is not an ideal workflow, and I am currently in the process of conceptualizing a way that remedies things like this (and also related stuff like Setting value validation).

Example for what I mentioned above. 
Note that I typed this out in GitHub, so syntax or name errors may be present.
```csharp
public abstract class DependantSetting<T, U> : SettingBase<T>
{
  [SerializeField] private SettingBase<U> dependency;
  [SerializeField] private U compareValue;
  [SerializeField] private SettingVisibility matchingVisibility = SettingVisibility.Visible;
  [SerializeField] private SettingVisibility nonMatchingVisibility = SettingVisibility.Disabled;

  protected override void OnInitialize()
  {
    if(dependency != null)
    {
      dependency.ValueChanged += DependencyValueChangedHandler;
      SetVisibilityWithoutNotify(GetGoalVisibility());  // Make sure the Setting starts out correctly
    }
  }

  private void DependencyValueChangedHandler(ValueChangeMode mode)
  {
    var visibility = GetGoalVisibility();
    SetVisibility(visibility);
  }

  private SettingVisibility GetGoalVisibility()
  {
    if(dependency == null)
      return Visibility;  // If there is no dependency configured, stick with current visibility

    var dependencyFulfilled = dependency.CompareEquality(dependency.CurrentValue, compareValue);
    return dependencyFulfilled ? matchingVisibility : nonMatchingVisibility;
  }
}
```

Some of the `SettingControl`s from the samples will automatically reflect any changes in a Setting's visibility; others may need to implement it manually. The easiest way to do that would be to provide a custom implementation for [`SettingControl<T,U>.OnVisibilityChanged`](https://github.com/zenvin-dev/UnitySettingsFramework/blob/caa8ed050058895b34fc01b201bfb37b57cc2f4c/Runtime/UI/SettingControl.cs#L88).

For an example implementation, see the [ToggleControl](https://github.com/zenvin-dev/UnitySettingsFramework/blob/main/Samples~/Settings%20Menu/Scripts/Controls/ToggleControl.cs).

**Comment by zenvin-dev** [comment]
Alternatively, you could reverse the process I described earlier and have the dependency maintain a list of dependees and their required values, and proactively update them when its value updates.

**Comment by YzZ-ZzY** [comment]
Thanks for the replies!

**Comment by zenvin-dev** [comment]
You're welcome!

**Comment by zenvin-dev** [comment]
Update:
It is now possible to add Components to Settings and Setting Groups. Those allow to do stuff like this more easily.

See commit e805487607056b6c302ba0b31d120f508e0cceff and the [`ConditionalVisibility`](https://github.com/zenvin-dev/UnitySettingsFramework/blob/main/Samples~/Components/ConditionalVisibility.cs) sample. @YzZ-ZzY 

Note: 
The feature works without issues as far as I could see, but I haven't tested it extensively.
So if you encounter any (apparent) bugs, let me know.
